# Generated by Django 4.2.7 on 2026-02-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('report_type', models.CharField(choices=[('prediction', '预测报告'), ('analysis', '数据分析报告'), ('model_eval', '模型评估报告'), ('summary', '综合报告')], max_length=20, verbose_name='报告类型')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('word', 'Word')], max_length=10, verbose_name='文件格式')),
                ('file_path', models.FileField(upload_to='reports/', verbose_name='报告文件')),
                ('description', models.TextField(blank=True, verbose_name='报告描述')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='起始日期')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
