# Generated by Django 4.2.7 on 2026-02-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('lstm', 'LSTM模型'), ('cnn', 'CNN模型'), ('lstm_cnn', 'LSTM+CNN混合模型'), ('collaborative', '协同过滤')], max_length=20, verbose_name='模型类型')),
                ('model_version', models.CharField(max_length=50, verbose_name='模型版本')),
                ('location', models.CharField(max_length=200, verbose_name='预测点位')),
                ('prediction_time', models.DateTimeField(verbose_name='预测目标时间')),
                ('predicted_flow', models.IntegerField(verbose_name='预测流量')),
                ('actual_flow', models.IntegerField(blank=True, null=True, verbose_name='实际流量')),
                ('predicted_vehicle', models.IntegerField(default=0, verbose_name='预测车辆数')),
                ('predicted_pedestrian', models.IntegerField(default=0, verbose_name='预测行人数')),
                ('mae', models.FloatField(blank=True, null=True, verbose_name='MAE')),
                ('rmse', models.FloatField(blank=True, null=True, verbose_name='RMSE')),
                ('mape', models.FloatField(blank=True, null=True, verbose_name='MAPE(%)')),
                ('confidence_interval_low', models.FloatField(blank=True, null=True, verbose_name='置信下界')),
                ('confidence_interval_high', models.FloatField(blank=True, null=True, verbose_name='置信上界')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='预测生成时间')),
            ],
            options={
                'verbose_name': '预测结果',
                'verbose_name_plural': '预测结果',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimePeriodLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('period', models.CharField(choices=[('morning_peak', '早高峰(7:00-9:00)'), ('evening_peak', '晚高峰(17:00-19:00)'), ('daytime', '白天平峰(9:00-17:00)'), ('night', '夜间(19:00-7:00)')], max_length=20, verbose_name='时段')),
                ('day_type', models.CharField(choices=[('workday', '工作日'), ('weekend', '周末'), ('holiday', '节假日'), ('special', '特殊日期')], default='workday', max_length=20, verbose_name='日期类型')),
                ('holiday_name', models.CharField(blank=True, max_length=50, verbose_name='节假日名称')),
                ('is_event', models.BooleanField(default=False, verbose_name='是否有大型活动')),
                ('event_name', models.CharField(blank=True, max_length=100, verbose_name='活动名称')),
                ('flow_factor', models.FloatField(default=1.0, help_text='相对于正常日的流量倍率', verbose_name='流量系数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '时段标签',
                'verbose_name_plural': '时段标签',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TrafficFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='时间戳')),
                ('location', models.CharField(max_length=200, verbose_name='监测点位')),
                ('camera_id', models.CharField(blank=True, max_length=50, verbose_name='摄像头编号')),
                ('vehicle_count', models.IntegerField(default=0, verbose_name='车辆数量')),
                ('pedestrian_count', models.IntegerField(default=0, verbose_name='行人数量')),
                ('bicycle_count', models.IntegerField(default=0, verbose_name='自行车数量')),
                ('motorcycle_count', models.IntegerField(default=0, verbose_name='摩托车数量')),
                ('truck_count', models.IntegerField(default=0, verbose_name='卡车数量')),
                ('total_flow', models.IntegerField(default=0, verbose_name='总流量')),
                ('avg_speed', models.FloatField(blank=True, null=True, verbose_name='平均速度(km/h)')),
                ('occupancy_rate', models.FloatField(blank=True, null=True, verbose_name='道路占有率(%)')),
                ('source', models.CharField(choices=[('sensor', '传感器'), ('camera', '摄像头(YOLO检测)'), ('manual', '手动录入'), ('api', 'API接入')], default='camera', max_length=20, verbose_name='数据源')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='检测置信度')),
                ('is_cleaned', models.BooleanField(default=False, verbose_name='是否已清洗')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '交通流量数据',
                'verbose_name_plural': '交通流量数据',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='时间戳')),
                ('location', models.CharField(max_length=200, verbose_name='区域')),
                ('weather_type', models.CharField(choices=[('sunny', '晴天'), ('cloudy', '多云'), ('rainy', '雨天'), ('foggy', '雾天'), ('snowy', '雪天'), ('overcast', '阴天')], max_length=20, verbose_name='天气类型')),
                ('temperature', models.FloatField(verbose_name='温度(°C)')),
                ('humidity', models.FloatField(verbose_name='湿度(%)')),
                ('wind_speed', models.FloatField(default=0, verbose_name='风速(m/s)')),
                ('visibility', models.FloatField(default=10.0, verbose_name='能见度(km)')),
                ('precipitation', models.FloatField(default=0, verbose_name='降水量(mm)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '气象数据',
                'verbose_name_plural': '气象数据',
                'ordering': ['-timestamp'],
            },
        ),
    ]
