# Generated by Django 4.2.7 on 2026-02-27 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traffic_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficflow',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AlterUniqueTogether(
            name='timeperiodlabel',
            unique_together={('date', 'period')},
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='预测者'),
        ),
        migrations.AddIndex(
            model_name='trafficflow',
            index=models.Index(fields=['timestamp', 'location'], name='traffic_dat_timesta_5f45a9_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficflow',
            index=models.Index(fields=['camera_id'], name='traffic_dat_camera__b8251a_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['prediction_time', 'location'], name='traffic_dat_predict_6335da_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['model_type'], name='traffic_dat_model_t_f36537_idx'),
        ),
    ]
